### ISSUE TITLE
Refresh download link address

### ISSUE THREAD

**Issue by IIIPeAceIII** [AminBhst/brisk#1]
A feature which gives ability to make changes in link address of downloads. Very useful when the links get expired.

**Comment by AminBhst** [comment]
That would be very useful indeed. I will definitely implement this feature for future versions. Thank you for the great suggestion.

**Comment by AminBhst** [comment]
This feature is now available in [version 1.0.1](https://github.com/AminBhst/brisk/releases/tag/1.0.1)
