### ISSUE TITLE
Grabbing videos/audio

### ISSUE THREAD

**Issue by jackuars7** [AminBhst/brisk#14]
Thank you for developing this application. I would like to suggest adding a feature to download videos from popular browsers. 
I believe it would be easier to do this once you have browser integration enabled.

**Comment by AminBhst** [comment]
@jackuars7 Thank you for the suggestion. Browser integration is absolutely my top priority for the next major release. I currently only have time for minor bug fixes but hopefully I'll be able to start the development of a dedicated browser extension in the next few months.

**Comment by AminBhst** [comment]
Available in v.2.1.0
