### ISSUE TITLE
Add system tray support

### ISSUE THREAD

**Issue by AminBhst** [AminBhst/brisk#20]
Package needed: [system_tray](https://pub.dev/packages/system_tray) or [tray_manager](https://pub.dev/packages/tray_manager)
- It is important to check whether or not a minimized to tray window can be brought to front upon receiving download requests from the browser extension. If that is not possible, [multiple window support](https://github.com/AminBhst/brisk/issues/18) could solve this problem. In the meantime, as a workaround we can send a system notification when a download request has been captured from the browser
- Ask the user whether or not the app should be moved to tray when the close button is clicked. A 'remember this decision' option also has to be added which requires a new app setting entry.

**Comment by ZorinFoss** [comment]
Hi @AminBhst

you can check this [project](https://github.com/GopeedLab/gopeed/tree/main/ui/flutter) to implement system tray support

**Comment by AminBhst** [comment]
@ZorinFoss Sure. The problem isn't that I faced issues trying to implement it, it's that I just haven't had enough time to work on it. It will most likely be included for the next release.

**Comment by ZorinFoss** [comment]
i hope so, system tray is very important part.

**Comment by AminBhst** [comment]
For sure. It's my priority right now. Hopefully it will be done by next week.

**Comment by AminBhst** [comment]
Now available in [V1.4.3](https://github.com/AminBhst/brisk/releases/tag/v1.4.3)

**Comment by ZorinFoss** [comment]
@AminBhst Well done!

**Comment by ZorinFoss** [comment]
the browser extension does not work after the last update

**Comment by AminBhst** [comment]
> the browser extension does not work after the last update

You sure? I just checked and it worked fine. I didn't really change much about the browser extension behavior with this update.

**Comment by AminBhst** [comment]
@ZorinFoss Also would please tell me what the exact package name for ```appindicator3-0.1``` is on Arch? I want to add it to the README but I don't own an Arch OS to test it myself.

**Comment by ZorinFoss** [comment]
it's `libappindicator-gtk3`

**Comment by ZorinFoss** [comment]
> > the browser extension does not work after the last update
> 
> You sure? I just checked and it worked fine. I didn't really change much about the browser extension behavior with this update.

i test on brave and on chromium and it does not work.

**Comment by AminBhst** [comment]
> > > the browser extension does not work after the last update
> > 
> > 
> > You sure? I just checked and it worked fine. I didn't really change much about the browser extension behavior with this update.
> 
> i test on brave and on chromium and it does not work.

Could you also test it on Firefox as well and let me know if it works? Also try it with different links.
