### ISSUE TITLE
Add launch on startup support

### ISSUE THREAD

**Issue by AminBhst** [AminBhst/brisk#21]
Brisk should optionally be able to launch at startup since the browser extension is always active by default. The possibility of starting up in the system tray must also be investigated.

Package needed: [launch_at_startup](https://pub.dev/packages/launch_at_startup)

**Comment by dhanesh12twice** [comment]
Hi @AminBhst could be you more specific

**Comment by AminBhst** [comment]
By using the plugin I mentioned, brisk should have the ability to launch on startup. There should also be a new setting entry that allows the user to control the launch on startup behavior (turn it on or off). That's all there is to it
