### ISSUE TITLE
Uncheck selected rows after clicking on download or stop button

### ISSUE THREAD

**Issue by AminBhst** [AminBhst/brisk#25]
This is merely a minor UX improvement. Since It's kind of a hassle for the user to check rows and click download/stop button and then uncheck the rows again, It's better to automatically uncheck the selected rows when these buttons are pressed. 

For any potential contributors, check the ```pluto_grid_util``` file to get an idea on how to uncheck rows. The buttons are also in the ```top_menu``` file. 

Contributions are welcome and appreciated.

**Comment by qmohitsingh** [comment]
@AminBhst I am interested in working on this. Could you please assign it to me?

**Comment by AminBhst** [comment]
@qmohitsingh I'm not gonna work on this myself as long as you're working on it so if you were no longer interested or faced any issues could you please let me know?
Thanks

**Comment by qmohitsingh** [comment]
Hey @AminBhst, I haven't been able to get to this yet due to some other work commitments and the Thanksgiving break. I'm planning to wrap it up this coming week, if that works for you.

**Comment by AminBhst** [comment]
@qmohitsingh it's totally fine I only asked because I wanted to see if this can be included in the next release. No pressure I appreciate it 
thanks

**Comment by AminBhst** [comment]
@qmohitsingh Hey. Any updates on this?

**Comment by AminBhst** [comment]
[25c8f95](https://github.com/AminBhst/brisk/commit/25c8f95661357050c48e1dbeee16740bb40553bd)
