### ISSUE TITLE
Implement notifications for macOS

### ISSUE THREAD

**Issue by AminBhst** [AminBhst/brisk#3]
Brisk uses [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications) for handling its notifications on Linux. This package also supports macOS, but since I don't own a mac, I refrained from implementing it for this platform as I had no way of testing it.
The implementation is relatively straightforward as explained in the package's docs.
The file containing the notification logic is ```/lib/util/notification_util.dart```.
Contribution to this feature and any macOS-related features or bugs is greatly appreciated!

**Comment by Norman-w** [comment]
![image](https://user-images.githubusercontent.com/61178728/224007941-d0f5645e-f550-40bc-b51d-9417d7652ac3.png)
Got it on my dev environment but still doesn't work well due to #4 @AminBhst
