### ISSUE TITLE
[Announcement] Brisk is available now in ArchLinux AUR

### ISSUE THREAD

**Issue by ZorinFoss** [AminBhst/brisk#36]
Hi,

You can now download [brisk](https://aur.archlinux.org/packages/brisk-bin) from ArchLinux AUR

Thanks,

**Comment by AminBhst** [comment]
Hey. That's amazing thank you. I'll add the link to the README.

**Comment by AminBhst** [comment]
Hey @ZorinFoss. Are you interested in maintaining and keeping the AUR repo up-to-date with the latest releases?

**Comment by ZorinFoss** [comment]
Hey @AminBhst. The AUR package is maintained by someone has much knowledge than me. i ask him to add the brisk package and maintain it and he did. i mark the package as outdated and he will update it ASAP.

**Comment by AminBhst** [comment]
That's great thank you!

**Comment by AminBhst** [comment]
AUR link added to the README. Much appreciated!
