### ISSUE TITLE
Can't download from send.cm

### ISSUE THREAD

**Issue by Samson7** [AminBhst/brisk#40]
I tried to download a file from send.cm([send.cm](https://send.cm/oee4fr2kbqa5)) and got an error (browser downloads the file normally)
![Screenshot (3)](https://github.com/AminBhst/brisk/assets/19408982/d4aee834-a375-4ba5-b2ba-af0574cd9563)

**Comment by AminBhst** [comment]
This link is not working now apparently (404). Let me know ff there were any other links that you faced the same issue with
