### ISSUE TITLE
Background service enhancement

### ISSUE THREAD

**Issue by Samson7** [AminBhst/brisk#41]
It would be cool to make a a service that will work in the background, to be able to unload the UI because the UI consumes a lot of RAM.

**Comment by Samson7** [comment]
Yes at first the memory consumption was 74 MB, but now it has decreased to 38 MB. Its's already better, but still a little bit much, consumption around 15 Mb would be nicer. My download speed is 10-12 MB/s.

**Comment by AminBhst** [comment]
I will try my best to optimize it as much as I can but a lot of it goes back to the Flutter platform itself and how things are handled internally. What comes to my mind right now is to add a low resource usage option to the settings which allows the download buffer to be flushed to the disk more frequently, in other words, the receiving bytes will not live on memory as much as they do by default. This might come with some caveats tho such as a longer file assembling process. On top of that I can also limit the frequency of UI updates which will lower the CPU usage as well. 
Thanks for the suggestion. I will add these features for future releases.

**Comment by AminBhst** [comment]
Low Resource Mode is now available in [v1.4.4](https://github.com/AminBhst/brisk/releases/tag/v1.4.4)
