### ISSUE TITLE
Suggestions of  best open source extensions and cli downloaders engines to support downloading embedded video streams 

### ISSUE THREAD

**Issue by trimechee** [AminBhst/brisk#42]
Hello, thank you so much for this  new great awesome fantastic download manager ! 💯 🥇

I have request please :  add support for downloading videos from embed streaming videos sites 
and may be  integrating some of these great rare  open-source regulary updated extensions and tools may help to detect embed complex videos from streaming videos and make our beloved Brisk Download manager  more stronger and more efficient to detect and download all kind of embed videos, thank you !

Best of open source video downloader extensions :

https://github.com/chandler-stimson/live-stream-downloader

https://github.com/puemos/hls-downloader

https://github.com/xifangczy/cat-catch/blob/master/README_en.md

https://github.com/sebaro/ViewTube
https://github.com/sebaro/SaveTube

https://github.com/xifangczy/URLProtocol

https://github.com/andy-portmen/open-in-vlc/

https://github.com/ray-lothian/Easy-Video-Downloader
https://webextension.org/listing/easy-video-downloader.html

https://github.com/54ac/stream-detector

https://github.com/inbasic/bulk-media-downloader
https://github.com/inbasic/turbo-download-manager-v2

https://github.com/woodruffw/ff2mpv
3DYD Youtube Source
https://ys.3dyd.com/

https://github.com/iawia002/lux

https://github.com/soimort/you-get

https://github.com/AminBhst/brisk-browser-extension

https://github.com/zaidka/cliget

https://github.com/kanishka-linux/hlspy

https://github.com/selsta/hlsdl

https://github.com/aclap-dev/vdhcoapp

https://github.com/CoolnsX/hls_downloader

https://sites.google.com/site/linkgopher/

https://github.com/emarsden/dash-mpd-cli

https://github.com/nilaoda/N_m3u8DL-CLI
https://github.com/nilaoda/N_m3u8DL-RE
https://github.com/globocom/m3u8

EDIT :  and also 

https://github.com/agalwood/Motrix

https://github.com/AminBhst/brisk

https://github.com/mhogomchungu/media-downloader
https://github.com/mhogomchungu/media-downloader/wiki/Extensions

https://github.com/giantpinkrobots/varia

https://github.com/filecxx/FileCentipede
https://filecxx.com/en_US/index.html#features

edit : and : 
https://github.com/aandrew-me/ytDownloader
https://ytdn.netlify.app/

https://github.com/kannagi0303/yt-dlp-gui

https://github.com/ytdl-official/unlock

https://github.com/setvisible/ArrowDL
https://www.arrow-dl.com/

https://github.com/giantpinkrobots/varia
https://giantpinkrobots.github.io/varia/

https://github.com/ErrorFlynn/ytdlp-interface

https://github.com/database64128/youtube-dl-wpf
https://cube64128.xyz/

https://github.com/Maxstupo/ydl-ui

https://github.com/jeanslack/Videomass
https://jeanslack.github.io/Videomass/

https://oleksis.github.io/youtube-dl-gui/
https://github.com/oleksis/youtube-dl-gui

https://github.com/KurtBestor/Hitomi-Downloader

https://github.com/KikoPlayProject/KikoPlay
https://kikoplay.fun/

https://curl.se/

https://nodejs.org/en

https://www.electronjs.org/

https://github.com/SeaHOH/ykdl

https://github.com/CoolnsX/dra-cla

https://github.com/nilaoda/BBDown

Video m3u8 Sniffer - Find HLS Streaming URLs
M3U8 finder and HLS player
http://sigmafxdx.com/m3u8Sniffer/

https://github.com/CoolnsX/hls_downloader
https://coolnsx.github.io/

scripts and tools  :

https://github.com/Momo707577045/m3u8-downloader
https://github.com/Momo707577045/media-source-extract
https://github.com/Momo707577045/tinypng-script-with-cache
http://blog.luckly-mjw.cn/tool-show/m3u8-downloader/index-en.html
https://segmentfault.com/a/1190000025182822

Native HLS playback
by Gaetan Hervouet
https://github.com/ghouet/chrome-hls
Native MPEG-Dash + HLS Playback
by David Cavar
https://github.com/Palethorn/native-adaptive-streaming
https://cavar.net/

https://github.com/pystardust/ani-cli
https://github.com/justfoolingaround/animdl

https://github.com/spencerwooo/onedrive-vercel-index
https://github.com/alist-org/alist

https://github.com/helloxz/ccaa

edit : integration with web browsers : 

https://github.com/AminBhst/brisk-browser-extension

https://github.com/ugetdm/uget-integrator

and :

https://github.com/persepolisdm/Persepolis-WebExtension

https://github.com/filecxx/FileCentipede

https://github.com/subhra74/xdm-integration-module
https://github.com/subhra74/xdm-browser-monitor
https://github.com/subhra74/xdm-helper-chrome
https://github.com/subhra74/xdm-firefox-old

https://github.com/ginuerzh/gost/blob/master/README_en.md
https://github.com/kanishka-linux/hlspy
https://curl.se/
https://nodejs.org/en
https://www.electronjs.org/
https://github.com/SeaHOH/ykdl
https://github.com/selsta/hlsdl

********

https://github.com/iamtalhaasghar/yewtube
https://github.com/mps-youtube/yewtube/issues/1191
https://iamtalhaasghar.github.io/yewtube/

https://github.com/otisdog8/termitube

https://erickutcher.github.io/#HTTP_Downloader

https://github.com/nilaoda/BBDown

https://github.com/the1812/Bilibili-Evolved

https://github.com/kengwang/BiliDuang

https://github.com/MotooriKashin/Bilibili-Old

https://github.com/sodaling/FastestBilibiliDownloader

https://github.com/pystardust/ytfzf
https://github.com/justfoolingaround/fast-yt-search

https://github.com/anasty17/mirror-leech-telegram-bot
https://github.com/junedkh/jmdkh-mltb

**Comment by AminBhst** [comment]
Hey @trimechee, Thank you for your support and suggestion. Yes there is already another open issue regarding this feature and I've had it on my mind for quite some time now. I'm currently working on a new connection management algorithm that takes quite some time and effort. After that feature is released I will most likely start working on downloading videos from embed streams. The links you provided will be very helpful in its development. Thank you.

**Comment by AminBhst** [comment]
That's perfect. I really appreciate it!

**Comment by AminBhst** [comment]
No problem. I'm always open to ideas and suggestions. Yes as you mentioned I don't imagine I will be able to integrate all of them or even directly integrate any of them. However, taking a look at their source code and examining how these tools function can definitely be very helpful. I can't promise this feature any time soon both due to how busy I am irl and the complicated feature that I'm currently working on. However, since brisk is my passion project I will always try to enhance it and make it more competitive to other download managers.
Thanks again for your kind words and support.

**Comment by AminBhst** [comment]
Brisk doesn't work in the background if it's closed. With the most recent update there is a tray option available which will minimize the application to the tray (if the user wishes to do so). But if it is also closed from the tray, brisk will not have any background process open.

**Comment by trimechee** [comment]
Awesome !! Thank you very much :) 💯

**Comment by AminBhst** [comment]
Regarding the browser extension, I think your suggestion is valid. But since it's unrelated to this issue, I'd appreciate it If you would kindly open a new issue in the browser extension repository for this feature (alerting the user that brisk is not currently running) and I will try to plan it for future releases.

**Comment by trimechee** [comment]
Hello, I was happy when I discovered filecentripede download manager but in some streaming video players, like in this site : 

https://v5.voiranime.com/anime/boku-dake-ga-inai-machi/

and even if I choose "1" for the number of threads, the downloaded video is divided into very small parts which prevents me from watching the video while it is downloading and I have to wait for the download to finish, we hope Brisk will add an option to preview/watch the video while downloading, I tried with coc coc browser which can download streamig videos and I can preview/watch while downloading the video, thank you!

**Comment by AminBhst** [comment]
It's plausible to implement that. But it's a VERY niche feature. It's a feature that's not typically expected of a download manager. There are other major features that take priority like the new connection management algorithm, torrent support, downloading embedded streams, etc. But you can open a new issue for this feature so that I don't miss it in the future. This issue thread is getting a bit too long with feature requests that are unrelated to the title of this issue. Please open a new issue per feature request. Thanks
