### ISSUE TITLE
Add video streaming capability

### ISSUE THREAD

**Issue by trimechee** [AminBhst/brisk#43]
Hello, thank you so much for this awesome great fantastic new download manager !! 💯 🥇

I discovered while downloading from streaming sites that in some streaming video players, like in this site :

https://v5.voiranime.com/anime/boku-dake-ga-inai-machi/

and even if I choose "1" for the number of threads, the downloaded video is divided into very small parts which prevents us from watching the video while it is downloading and I have to wait for the download to finish to watch the donwloaded video, so please we hope our beloved Brisk Download Manager will add an option to preview/watch the video while downloading, I tried with coc coc browser which can download streamig videos and thus we can play file while it's still downloading and preview/watch while downloading the video, thank you !

EDIT :

Yes  we can think this option request is a niche feature 👍  but personnaly i think it is an important and the most important feature of a donwload manager, already it allows us to avoid the possible banning of our IP address by setting the number of threads to "1" if for example when downloading episodes of anime which have 700 episodes!

in addition the wifi can become unstable very weak when a lot of family members connect, and if we watch streaming, the viewing will be jerky lag interrupted if the video is in HD if our internet connection is weak, in addition the downloaded video can be very long and waiting for the download to finish can be annoying...plus I have done tests and downloading videos from streaming sites with number of threads "1" is very fast, stable and it is more ecological and saves our battery resources!

Coc coc browser says that its internal downloader has 8 threads to speed up the downloads however we can preview the downloaded video so I think coc coc browser downloads first part of the video first then increase the number of threads to increase the speed....

Thank you very much :)

EDIT : 

Hello, I talked to the developer of FileCentipede about this probleme and this is his answer....maybe it cOULD help to add the great video streaming capability  :  

"For streaming media, the use of a single thread or multiple threads for downloading makes no difference. During the download process, the downloader creates independent files for each segment locally, which are then merged into a single file after downloading. This is why the file cannot be played. To resolve this, I can add an option in the future to enable sequential downloading using only one connection and creating a single file, allowing the player to function properly. However, the player's fast-forward and rewind functions may not be available. While many players support direct playback of m3u8 files, they may not bypass certain download restrictions or decrypt content like FileCentipede does, unless I make a new video player. In the absence of a perfect solution, I will work on addressing this issue in the future.

Thank you for your feedback, and I will strive to resolve this problem in subsequent updates."

and this was my response : 

"Mr Filecxx , you explained to us : "unless I make a new video player.", oh we thank you very much ! we know it's a very difficult and complicated and complex task and we don't want to tire you out, so if potplayer or vlc player doesn't cannot "bypass certain download restrictions or decrypt content", perhaps the source code of these open source and powerful video players could help to find a solution or add patches or fix evental bugs with playback.....:

https://github.com/KikoPlayProject/KikoPlay

https://github.com/zaps166/QMPlay2

https://github.com/coslyk/moonplayer

https://github.com/vzhd1701/gridplayer

https://github.com/tsl0922/ImPlay

https://github.com/mpc-qt/mpc-qt

https://github.com/mpvnet-player/mpv.net

https://github.com/smplayer-dev/smplayer

https://github.com/422658476/MPV-EASY-Player

**Comment by AminBhst** [comment]
https://github.com/AminBhst/brisk/issues/42#issuecomment-2034422293

**Comment by trimechee** [comment]
Hello Mr @AminBhst , i talked to the developer of FileCentipede about this probleme and this is his answer....maybe it can help to add the great video streaming capability  :  

"For streaming media, the use of a single thread or multiple threads for downloading makes no difference. During the download process, the downloader creates independent files for each segment locally, which are then merged into a single file after downloading. This is why the file cannot be played. To resolve this, I can add an option in the future to enable sequential downloading using only one connection and creating a single file, allowing the player to function properly. However, the player's fast-forward and rewind functions may not be available. While many players support direct playback of m3u8 files, they may not bypass certain download restrictions or decrypt content like FileCentipede does, unless I make a new video player. In the absence of a perfect solution, I will work on addressing this issue in the future.

Thank you for your feedback, and I will strive to resolve this problem in subsequent updates."


and this was my response : 

"Mr Filecxx , you explained to us : "unless I make a new video player.", oh we thank you very much ! we know it's a very difficult and complicated and complex task and we don't want to tire you out, so if potplayer or vlc player doesn't cannot "bypass certain download restrictions or decrypt content", perhaps the source code of these open source and powerful video players could help to find a solution or add patches or fix evental bugs with playback.....:

https://github.com/KikoPlayProject/KikoPlay

https://github.com/zaps166/QMPlay2

https://github.com/coslyk/moonplayer

https://github.com/vzhd1701/gridplayer

https://github.com/tsl0922/ImPlay

https://github.com/mpc-qt/mpc-qt

https://github.com/mpvnet-player/mpv.net

https://github.com/smplayer-dev/smplayer

https://github.com/422658476/MPV-EASY-Player

**Comment by AminBhst** [comment]
Ah I now understand what you mean by streaming. This is also how brisk works btw. If by streaming you mean playing the file as its downloading using its temp files, it's not gonna work with the current design of the download core. I will also need to implement a sequential writing mode for it to work properly. I didn't quite understand what the developer meant by "they may not bypass certain download restrictions or decrypt content like FileCentipede does". I don't know what decryption he is referring to but aside from that, it is possible. The only problem is that I'm not sure if brisk will be able to append new bytes to the main file as it's being played (I don't know if the file will be locked by a video player). I will have to investigate that to ensure that it can be achieved. But writing an embedded video player is out of the question lol. It's way too much work for a feature that is typically not expected of a download manager.

**Comment by trimechee** [comment]
Ok, we understand :) I just talked about that  just as suggestion  filecentped code could be a source of inspiration if this functionality is implemented....he mos important feature is to able to detect  videosbecause with the download speed, the downloading happens faster and faster so yes sequential donwload is not a very important function :)

**Comment by trimechee** [comment]
I just say "maybe it can help to add the great video streaming capability " just to copy takes it from the issue, apparently the title of the issue was changed, the old title was play files while downloading.... and FDM (free download manager) added this function in its very latest version so this function seems more and more popular among users because FDM has put a vote on its forum where users vote for the features they want to be added to FDM.....

given the download speed and improvement of the internal download managers of browsers, it seems people mainly use the donwload managers to download video streaming....

**Comment by trimechee** [comment]
"streaming capability", means often websites or web browsers limit the quality of the video buffer to 30 seconds, 60 seconds even if the video is in high quality and the internet connection is weak which leads to jerky lag....except on YouTube which has optimized its codecs AV1, vp9..... I cannot playback HD or 1080 p videos on streaming sites and sometimes only HD quality is offered and not standard quality....so a download manager with sequential downloading would perhaps allow to have the comfort of viewing 1080p streaming video even with a weak internet connection without waiting for the download to finish and without needing to take out an expensive internet package....but we understand it's complicated and that's not the hardly if it's tiring :) people say the famous extension videodonwloadhelper adds a qr code on the downloaded video so it becomes more and more difficult to download videos via free program....and we thank you for having planned this function to download the videos! 💯 🥇

**Comment by AminBhst** [comment]
Actually it's not that difficult to implement. It takes some adjustments to create a modified version of the download core to write files sequentially which could be used later on based on the app settings. If video players don't lock the file, it should hopefully go smoothly.

**Comment by trimechee** [comment]
Ohh interesting ! Thank you so much :) yes we use already our favourite video players like qmplay2 and potplayler and moonplayer.....and we hope there will be not need to use other media players to play the files donwloaded by download managers ! 👍 💯

**Comment by trimechee** [comment]
Hi Mr @AminBhst , how are you ? just to inform you about this  Great news, i said to you i can no longer seen and playback video while donwloading when i use cat catch and live stream donwloader extension, but this night alhamdoulilAllah,  i find the solution to display temporary video in chromium browsers and fix this major problem !! 

https://github.com/win32ss/supermium/issues/1064

**Comment by trimechee** [comment]
update : temporary video of cat catch is not displayed when i use supermium, catsxp browsers, but displayed when i use chrome for windows 7, so we should use chrome browser

**Comment by AminBhst** [comment]
I won't be supporting temporary videos in the browser extension itself. I Will probably only support via brisk in a future version. I do however show some information about the stream that is about to be downloaded. For example for a master playlist, I will display the resolution, framerate, and duration for each Item so it should be pretty clear which stream is about to be downloaded for now.

**Comment by AminBhst** [comment]
Regardless, I don't understand the relevance of cat-catch's behavior to Brisk. I won't be using cat-catch as part of the extension update.

**Comment by trimechee** [comment]
@AminBhst  Regardless, I don't understand why your answers are so cold instead of just telling me thank you for these sensational discoveries that fix a major bug,

already out of politeness and to thank you, me i am not using brisk because i have windows 7, but  I inform you for your own interest of this major bug and its solution, because for months I have been suffering from preview problems with potplayer, download bugs and I offer you my rare vital discoveries; we should enable option "continue running applications in the background after closing chrome"

chrome://settings/system and use chrome to avoid bugs;

it's in your interest because already, you told me you are an anime fan, so cat catch can help you download anime and I already offered you my rare publication gathering thousands of anime and streaming sites, updated annuaries...

secondly it doesn't matter whether it talks about brisk or not, I share out of politeness my discovery, and I offer you a tip that can impact brisk, imagine a user like me deactivates the option "continue running applications in the background after closing chrome"!, and he does not use chrome, and brisk cannot capture the links, the user will ask you to fix the problem, you will waste your time investigating and looking for how to fix this bug, and I will spare you that, we can think chromium browsers download or intercept links or work the same way but this is not the case, and my tips will fix future bugs related to brisk, the brisk extension can not work properly if you disable the option "continue running applications in the background ...", for example you can tell users to use chrome to fix possible bugs ....

since I talked about the former emperor of persia and the battle for faith reigns in Iran, and I criticize takumi of intial d who kisses a girl outside of marriage, I feel your messages have become cold, why?

**Comment by trimechee** [comment]
Thank you Mr @AminBhst  for your polite message and I apologize for my message being a bit too spicy lol ! 💯 

already personally, I find it logical to talk about this here: I tired you, I flooded you with messages, hundreds of software suggestions so that you add sequential download and support detect media to Brisk, I asked you this not to tire you but I tried cat catch, live stream downloader, file centipede, neat download maager, hls-downloader, FDM, arrowdl.....and I could not see and playback temporary video while downloading , it is vital for me because my connection is weak, my cpu is weak old , playback in browser lag jerks, and I do not like to wait for the end of slow downloads....

now after months or years of suffering, I finally discover the origin of these problems of I cannot preview video with potlayer using cat catch, open in vlc , the temporary video does not display, the origin of all these nightmares is I want to make the browser lighter so I disabled without science the vital option for downloading and previewing: "

"continue running applications in the background after closing chrome"

chrome://settings/system

and temporary video is displayed in supermium, catsxp browser when I use live stream downloader, but not when I use cat catch, so I discover by finding and using updated chrome 130 for windows 7 os, I can see temporary video of cat catch using chrome which seems to work differently from supermium and catsxp ....

i'm telling you about this, already maybe people have seen my issue and this solution can save them from months or years of suffering, and we no longer need to use dangerous ineffective crack of IDM, and also it's a way to inform the generous and compassionate Mr Amin that he no longer needs to add the feature "detect media" to Brisk, I feel guilty for tiring you to integrate this complex feature and you told me you are tired by the Brisk development, so, at least for now, as long as I use windows 7 os lol and as long as the cat catch and live stream downloader extensions display the temporary video and I can playback it, then I withdraw my request and I no longer ask Mr Amin to bother continuing to develop the complex "download media" feature, thanks :)

**Comment by AminBhst** [comment]
Aaah that's interesting thank you. I will keep that in mind if I ran into an issue that could stem from this. No lol you shouldn't feel guilty. First of all, I always had the idea of downloading video streams from the browser since the day I started Brisk because I wanted it to get to a point where it could replace most features of IDM while being completely free and open-source. Also, I won't just work on a feature that I don't find interesting or useful just because someone asked for it. I don't make a single penny off of Brisk so why would I lol. I will only do so when I find it beneficial to the project and worth my time. All the work I put into it directly impacts my own usage as well since I naturally use my own download manager all the time. So don't feel guilty about it. I will never work myself to death just because someone asks me to xd.

**Comment by trimechee** [comment]
Great , thank you :) i thnink , it 's time, as Brisk reaches maturity and hopefully will become even more popular, it's time to highlight the "sponsor" button donate via paypal, buymecoffe, patreon, crypto..." in the Brisk github page and in the Brisk start interface to encourage users to participate in the development of this great project, thank you!

**Comment by AminBhst** [comment]
Yeah that's something I wanted to do but unfortunately, since I live in iran, I don't have access to any of these payment services. The only possible option I have is crypto.

**Comment by trimechee** [comment]
I have seen some programs or sites ask their users to watch a minute or 2 minutes of advertising on certain websites so they will be paid....maybe add the option "display not heavy light ads" when starting Brisk which will open the web browser....

trump wants to develop crypto currency, which risks becoming the universal world currency....

i heard the iranian state has officially lifted the ban on whatsapp and google play, i think that leaves some hope for paypal and other services , i think the fall of the criminal syrian regime, barbaric russia entangled in ukraine, trump and zionists who want to destroy the iranian nuclear program (obviously we hope you will be in secret Mr Amin :), i think the iranian regime will become more flexible and tolerant and will hopefully allow paypal, buymecoffe, patreon....it's a shame to deprive talented iranian developers of income :(

we also hope the iranian regime will allow a sunni mosque to Tehran, it's not normal, the employees of the embassies can't find anywhere to pray, almost all the capitals of the world have mosques for Sunnis, it's really crazy to hate the virtuous mother of believers our mother Aicha and the pious apostles of the prophet peace be upon him, we hope Iran will live in peace and return to its Sunni origins biithniAllah !

**Comment by AminBhst** [comment]
Well unfortunately the problem regarding this issue isn't the regime itself. All these services are inaccessible due to sanctions from the US. There is no access to the international banking system. Political topics can go on for ages lol but GitHub isn't really the place for such that. It's not a safe space for it either. There is nothing we can do about that. I hope things get better for everyone.

**Comment by trimechee** [comment]
In sha Allah, yes, sorry I didn't plan to talk about all that, I can delete my post if you want :) or you you can delete it, there is no problem :)

obviously we support Iran when it attacks the zio ni sts, but supporting Palestine must never be a pretext to support shady regimes...the USA abuses too much, it's pathetic that a so-called powerful country is the lackey and slave of zio ni st....anyway we hope peace and prosperity and faith for great iranian people and this great prestigious country which is Iran :)

**Comment by AminBhst** [comment]
No it's okay. Thank you appreciate that. I also wish the best for you, your people and your country.

**Comment by trimechee** [comment]
Thank you :) 💯
