### ISSUE TITLE
Existing task checking mistake

### ISSUE THREAD

**Issue by Norman-w** [AminBhst/brisk#5]
![image](https://user-images.githubusercontent.com/61178728/224008991-04e1ad56-1aaa-4255-9f27-91bb42940f08.png)

1. Create a task and download it.
2. Remove the downloaded file when it is finished.
3. Re-create a new task with the same URL, then we will see this notice.

**Comment by AminBhst** [comment]
@Norman-w Hmm that is odd. The way it works is that it checks whether or not the file already exists in the same directory or if a download item for the same file exists in the database. So if you delete both the download item and its file, this error should not appear. I wasn't able to replicate this for myself based on the provided steps. Are you sure you have deleted the same file? Could you delete the app database which is located in the Documents directory and delete the entire brisk download folder as well and try again?

**Comment by Norman-w** [comment]
> @Norman-w Hmm that is odd. The way it works is that it checks whether or not the file already exists in the same directory or if a download item for the same file exists in the database. So if you delete both the download item and its file, this alert should not appear. I wasn't able to replicate this for myself based on the provided steps. Are you sure you have deleted the same file? Could you delete the app database which is located in the Documents directory and delete the entire brisk download folder as well and try again?

Now when you delete the download task in brisk, I didn't find the logic and prompt for me to delete the file from the hard disk.

Do you want keep [not remove file from hard disk] logic?

**Comment by AminBhst** [comment]
@Norman-w Deleting a download item only deletes its downloaded temp files. I will add an option later on to delete the file as well but as of right now, it doesn't exist.
