### ISSUE TITLE
Copy thr url adress m3u8 link with referrer and browser's user-agent string to preview streaming video in vlc or potplayer

### ISSUE THREAD

**Issue by trimechee** [AminBhst/brisk#55]
Hello, currently there is apocalypse disaster concerning the downloading of streaming video , streaming platforms have changed their streaming protocol or defense mechanism and it has almost become impossible to download streaming videos despite the fact that I have tried several extensions, a donwload mabager like FDM ......except this stream recorder extension for chrome can download streaming videos but it is not open source:

https://www.hlsloader.com/

the solution I found is to preview the streaming video, i.e. I copy the m3u8 link of the video and I paste it into potplayer or vlc using live stream downloader extension or cat-catch extension, but sometimes, it works, sometimes It doesn't work and currently with the apocalypse streaming websites, it no longer works.....

I talk about these problems to the extension developers and the cat-catch developer promised me that the next version will solve these problems in sha Allah, and the Live stream developer donwloader advised me to use the open- extension in-vlc to preview the videos without the need to download so I can get around the download bug but open-in vlc extension cannot preview the streaming streams for example in my favorite streaming site:

https://v5.voiranime.com/anime/kaiju-no-8-vf/

and I inform Mr Andy the developer of Open  in vlc 

https://github.com/andy-portmen/open-in-vlc/

who recently added major improvements such as the addition of the referrer and browser's user-agent string..... and I can now preview videos with vlc even hls videos all by closing the heavy web browser and I can even increase the network buffer in VLC for stable streaming despite weak wifi!!

so my suggestion Mr @AminBhst is to add the ability to preview videos with local media players like vlc or potplayer by adding option to copy the m3u8 link of the detected streaming video in order to paste the url link into potplayer or vlc which is useful essential when our laptop is weak or old and streaming in web browser lags freeze like in my 2012 laptop that I use after the plan of my modern laptop, thank you very much!

**Comment by AminBhst** [comment]
Hey. I did expect this feature to be hard to implement but based on what you said it will be even more difficult which is a shame.
 Sure. I will try to add this feature if I could get anywhere with the download of video/audio streams feature.

Currently blocked by #14

**Comment by AminBhst** [comment]
@trimechee One thing I'm curious about is that what kind of websites are doing this? What I mean by that is, I would assume that these security updates which make video steam downloads impossible are not done by all websites right? Generally speaking I think major websites would do this but I don't think this phenomena is happening with all websites that provide embedded streams.

**Comment by AminBhst** [comment]
That's really unfortunate. Hopefully, while I'm working on the new engine, other developers can find and implement a solution to combat this issue so that I can take inspiration from their work later on.

**Comment by AminBhst** [comment]
Thanks for the details explanation as always!
About the 32 bit version, I unfortunately won't be able to build that because the Flutter SDK don't support desktop 32 bit versions. It's a limitation by the framework using which Brisk was developed.
