### ISSUE TITLE
Add support of DownloadHelper CoApp and Flybird-downloader and N_m3u8DL-RE m3u8 mpd parsers to avoid WebAssembly's limitations videos up to 2GB only

### ISSUE THREAD

**Issue by trimechee** [AminBhst/brisk#59]
Hello, actually  I see the worrying trend of the majority of streaming platforms to only offer HD/1080p quality which have a mind-boggling weight and its disastrous consequences on web browsers which due to WebAssembly's limitations: only videos up to 2GB can be processed, like my favorite streaming site voiranime which in the past, offered 3 streaming platforms that have a reasonable standard SD video quality that is fast to download, but currently there is only one streaming platform that offers quality standard 480p i.e. a 24-minute anime episode weighs 100 MB, and maybe this platform will no longer offer SD quality and the weight of the videos will become even bigger with 1080p quality by default or 4k as a single video quality and the extension or the web browser can no longer download the video because their weight exceeds 2Gb, 

so in view of this future nightmare, we hope please that the awesome Brisk donwload manager will add compatibility with new awesome external m3u8 mpd parsers that can download large files and bypass the worrying limit of 2GB per video, 

so the famous extension Video DownloadHelper uses an open source external downloader parser : DownloadHelper CoApp to download some complicated videos, it is an open source external parser so maybe it will be a good idea to add support for this external downloader to solve some possible problems to download large videos in the future :

 https://github.com/aclap-dev/vdhcoapp/

and also please add the compatibility with this outstanding tool Flybird-downloader which is a video downloader tool that can download m3u8 videos, mpd videos, mp4 videos and resume downloading large files:

 https://github.com/youwen21/flybird-m3u8downloader 

and also the magnificent N_m3u8DL-RE  which is cross-platform, modern and powerful stream downloader for MPD/M3U8/ISM :: 

https://github.com/nilaoda/N_m3u8DL-RE 

and this is the rare ffmpeg online web site for online transcode or merge audio/video operations of Cat-Catch donwloader extension :  

 https://ffmpeg.bmmmd.com/ 

Thanks a lot!

**Comment by AminBhst** [comment]
Hey @trimechee. Thanks a lot that seems like an excellent tool! I'll definitely check it out since I'm about to start working on downloading streamed videos in the next few days. I'm sure the tools you've suggested so far will be very helpful. Appreciate it!

**Comment by AminBhst** [comment]
I'll try not to overwork myself :)
Thanks again. You're very helpful. Btw, if by any chance you're on discord I'd be happy to have you on my server. I think it can be helpful for me as well since I believe you have a very solid knowledge when it comes to the current state of downloading video streams which is a pretty huge feature to implement. It might be even more difficult than the v2.0.0 which I've been working on for months. So being able to ask you questions directly would be nice.

**Comment by AminBhst** [comment]
No bro don't apologize you're a great help. If you hadn't mentioned those tools, I would have had no idea such projects even existed.
I don't think redirecting the user to cat-catch is a UX friendly approach tbh and I don't even think I can intercept it using cat-catch itself. I'll probably have to look at their source code and get inspiration on how to do things.
It's okay bro. I hope your laptop gets fixed soon.

**Comment by AminBhst** [comment]
Well I mean why would he lol

**Comment by AminBhst** [comment]
Ah those kind of sites. I though you meant regular ones. Yeah fair enough

**Comment by AminBhst** [comment]
That's great thanks!
