### ISSUE TITLE
Managing macOS releases

### ISSUE THREAD

**Issue by AminBhst** [AminBhst/brisk#6]
Need a collaborator to manage Brisk releases for macOS. If you're interested, I can add you as a project collaborator to have access to github releases in order to upload the macOS binaries for each new release. This could probably also be achieved by using github actions as well, however I'm not aware of how the process is.
Your help is very much appreciated!

**Comment by AminBhst** [comment]
@Norman-w Are you by any chance interested?

**Comment by Norman-w** [comment]
Sure

**Comment by AminBhst** [comment]
@Norman-w Great. I have invited you to become a collaborator. For each new release I will create an issue regarding macOS build and assign it to you. I think with this also comes write access to project. You're free to push any changes related to macOS specific files like the `.entitlements` files which don't affect the project as a whole. However, for any changes regarding the project files please always submit a pull request.
Thank you
