### ISSUE TITLE
extensions dosent work

### ISSUE THREAD

**Issue by martialpeak** [AminBhst/brisk#61]
hi extensions dosent work
![{B9EB5650-6800-42EB-8CF2-4258799EF521}](https://github.com/user-attachments/assets/62a64690-6515-42fc-a55e-447564d84db4)

> 
(()=>{var e={544:(e,r,s)=>{"use strict";s.d(r,{y$:()=>n});var a=s(412);const g=3020;async function n(e){return await fetch(await async function(){return"http://localhost:"+await async function(){let e=await a.storage.sync.get(["briskPort"]);return e&&0!==Object.keys(e).length?e.briskPort:(await a.storage.sync.set({briskPort:g}),g)}()}(),{method:"POST",body:JSON.stringify(e)})}},412:function(e,r){var s,a;"undefined"!=typeof globalThis?globalThis:"undefined"!=typeof self&&self,s=function(e){"use strict";if(!globalThis.chrome?.runtime?.id)throw new Error("This script should only be loaded in a browser extension.");if(void 0===globalThis.browser||Object.getPrototypeOf(globalThis.browser)!==Object.prototype){const r="The message port closed before a response was received.",s=e=>{const s={alarms:{clear:{minArgs:0,maxArgs:1},clearAll:{minArgs:0,maxArgs:0},get:{minArgs:0,maxArgs:1},getAll:{minArgs:0,maxArgs:0}},bookmarks:{create:{minArgs:1,maxArgs:1},get:{minArgs:1,maxArgs:1},getChildren:{minArgs:1,maxArgs:1},getRecent:{minArgs:1,maxArgs:1},getSubTree:{minArgs:1,maxArgs:1},getTree:{minArgs:0,maxArgs:0},move:{minArgs:2,maxArgs:2},remove:{minArgs:1,maxArgs:1},removeTree:{minArgs:1,maxArgs:1},search:{minArgs:1,maxArgs:1},update:{minArgs:2,maxArgs:2}},browserAction:{disable:{minArgs:0,maxArgs:1,fallbackToNoCallback:!0},enable:{minArgs:0,maxArgs:1,fallbackToNoCallback:!0},getBadgeBackgroundColor:{minArgs:1,maxArgs:1},getBadgeText:{minArgs:1,maxArgs:1},getPopup:{minArgs:1,maxArgs:1},getTitle:{minArgs:1,maxArgs:1},openPopup:{minArgs:0,maxArgs:0},setBadgeBackgroundColor:{minArgs:1,maxArgs:1,fallbackToNoCallback:!0},setBadgeText:{minArgs:1,maxArgs:1,fallbackToNoCallback:!0},setIcon:{minArgs:1,maxArgs:1},setPopup:{minArgs:1,maxArgs:1,fallbackToNoCallback:!0},setTitle:{minArgs:1,maxArgs:1,fallbackToNoCallback:!0}},browsingData:{remove:{minArgs:2,maxArgs:2},removeCache:{minArgs:1,maxArgs:1},removeCookies:{minArgs:1,maxArgs:1},removeDownloads:{minArgs:1,maxArgs:1},removeFormData:{minArgs:1,maxArgs:1},removeHistory:{minArgs:1,maxArgs:1},removeLocalStorage:{minArgs:1,maxArgs:1},removePasswords:{minArgs:1,maxArgs:1},removePluginData:{minArgs:1,maxArgs:1},settings:{minArgs:0,maxArgs:0}},commands:{getAll:{minArgs:0,maxArgs:0}},contextMenus:{remove:{minArgs:1,maxArgs:1},removeAll:{minArgs:0,maxArgs:0},update:{minArgs:2,maxArgs:2}},cookies:{get:{minArgs:1,maxArgs:1},getAll:{minArgs:1,maxArgs:1},getAllCookieStores:{minArgs:0,maxArgs:0},remove:{minArgs:1,maxArgs:1},set:{minArgs:1,maxArgs:1}},devtools:{inspectedWindow:{eval:{minArgs:1,maxArgs:2,singleCallbackArg:!1}},panels:{create:{minArgs:3,maxArgs:3,singleCallbackArg:!0},elements:{createSidebarPane:{minArgs:1,maxArgs:1}}}},downloads:{cancel:{minArgs:1,maxArgs:1},download:{minArgs:1,maxArgs:1},erase:{minArgs:1,maxArgs:1},getFileIcon:{minArgs:1,maxArgs:2},open:{minArgs:1,maxArgs:1,fallbackToNoCallback:!0},pause:{minArgs:1,maxArgs:1},removeFile:{minArgs:1,maxArgs:1},resume:{minArgs:1,maxArgs:1},search:{minArgs:1,maxArgs:1},show:{minArgs:1,maxArgs:1,fallbackToNoCallback:!0}},extension:{isAllowedFileSchemeAccess:{minArgs:0,maxArgs:0},isAllowedIncognitoAccess:{minArgs:0,maxArgs:0}},history:{addUrl:{minArgs:1,maxArgs:1},deleteAll:{minArgs:0,maxArgs:0},deleteRange:{minArgs:1,maxArgs:1},deleteUrl:{minArgs:1,maxArgs:1},getVisits:{minArgs:1,maxArgs:1},search:{minArgs:1,maxArgs:1}},i18n:{detectLanguage:{minArgs:1,maxArgs:1},getAcceptLanguages:{minArgs:0,maxArgs:0}},identity:{launchWebAuthFlow:{minArgs:1,maxArgs:1}},idle:{queryState:{minArgs:1,maxArgs:1}},management:{get:{minArgs:1,maxArgs:1},getAll:{minArgs:0,maxArgs:0},getSelf:{minArgs:0,maxArgs:0},setEnabled:{minArgs:2,maxArgs:2},uninstallSelf:{minArgs:0,maxArgs:1}},notifications:{clear:{minArgs:1,maxArgs:1},create:{minArgs:1,maxArgs:2},getAll:{minArgs:0,maxArgs:0},getPermissionLevel:{minArgs:0,maxArgs:0},update:{minArgs:2,maxArgs:2}},pageAction:{getPopup:{minArgs:1,maxArgs:1},getTitle:{minArgs:1,maxArgs:1},hide:{minArgs:1,maxArgs:1,fallbackToNoCallback:!0},setIcon:{minArgs:1,maxArgs:1},setPopup:{minArgs:1,maxArgs:1,fallbackToNoCallback:!0},setTitle:{minArgs:1,maxArgs:1,fallbackToNoCallback:!0},show:{minArgs:1,maxArgs:1,fallbackToNoCallback:!0}},permissions:{contains:{minArgs:1,maxArgs:1},getAll:{minArgs:0,maxArgs:0},remove:{minArgs:1,maxArgs:1},request:{minArgs:1,maxArgs:1}},runtime:{getBackgroundPage:{minArgs:0,maxArgs:0},getPlatformInfo:{minArgs:0,maxArgs:0},openOptionsPage:{minArgs:0,maxArgs:0},requestUpdateCheck:{minArgs:0,maxArgs:0},sendMessage:{minArgs:1,maxArgs:3},sendNativeMessage:{minArgs:2,maxArgs:2},setUninstallURL:{minArgs:1,maxArgs:1}},sessions:{getDevices:{minArgs:0,maxArgs:1},getRecentlyClosed:{minArgs:0,maxArgs:1},restore:{minArgs:0,maxArgs:1}},storage:{local:{clear:{minArgs:0,maxArgs:0},get:{minArgs:0,maxArgs:1},getBytesInUse:{minArgs:0,maxArgs:1},remove:{minArgs:1,maxArgs:1},set:{minArgs:1,maxArgs:1}},managed:{get:{minArgs:0,maxArgs:1},getBytesInUse:{minArgs:0,maxArgs:1}},sync:{clear:{minArgs:0,maxArgs:0},get:{minArgs:0,maxArgs:1},getBytesInUse:{minArgs:0,maxArgs:1},remove:{minArgs:1,maxArgs:1},set:{minArgs:1,maxArgs:1}}},tabs:{captureVisibleTab:{minArgs:0,maxArgs:2},create:{minArgs:1,maxArgs:1},detectLanguage:{minArgs:0,maxArgs:1},discard:{minArgs:0,maxArgs:1},duplicate:{minArgs:1,maxArgs:1},executeScript:{minArgs:1,maxArgs:2},get:{minArgs:1,maxArgs:1},getCurrent:{minArgs:0,maxArgs:0},getZoom:{minArgs:0,maxArgs:1},getZoomSettings:{minArgs:0,maxArgs:1},goBack:{minArgs:0,maxArgs:1},goForward:{minArgs:0,maxArgs:1},highlight:{minArgs:1,maxArgs:1},insertCSS:{minArgs:1,maxArgs:2},move:{minArgs:2,maxArgs:2},query:{minArgs:1,maxArgs:1},reload:{minArgs:0,maxArgs:2},remove:{minArgs:1,maxArgs:1},removeCSS:{minArgs:1,maxArgs:2},sendMessage:{minArgs:2,maxArgs:3},setZoom:{minArgs:1,maxArgs:2},setZoomSettings:{minArgs:1,maxArgs:2},update:{minArgs:1,maxArgs:2}},topSites:{get:{minArgs:0,maxArgs:0}},webNavigation:{getAllFrames:{minArgs:1,maxArgs:1},getFrame:{minArgs:1,maxArgs:1}},webRequest:{handlerBehaviorChanged:{minArgs:0,maxArgs:0}},windows:{create:{minArgs:0,maxArgs:1},get:{minArgs:1,maxArgs:2},getAll:{minArgs:0,maxArgs:1},getCurrent:{minArgs:0,maxArgs:1},getLastFocused:{minArgs:0,maxArgs:1},remove:{minArgs:1,maxArgs:1},update:{minArgs:2,maxArgs:2}}};if(0===Object.keys(s).length)throw new Error("api-metadata.json has not been included in browser-polyfill");class a extends WeakMap{constructor(e,r=void 0){super(r),this.createItem=e}get(e){return this.has(e)||this.set(e,this.createItem(e)),super.get(e)}}const g=(r,s)=>(...a)=>{e.runtime.lastError?r.reject(new Error(e.runtime.lastError.message)):s.singleCallbackArg||a.length<=1&&!1!==s.singleCallbackArg?r.resolve(a[0]):r.resolve(a)},n=e=>1==e?"argument":"arguments",t=(e,r,s)=>new Proxy(r,{apply:(r,a,g)=>s.call(a,e,...g)});let m=Function.call.bind(Object.prototype.hasOwnProperty);const i=(e,r={},s={})=>{let a=Object.create(null),o={has:(r,s)=>s in e||s in a,get(o,A,l){if(A in a)return a[A];if(!(A in e))return;let c=e[A];if("function"==typeof c)if("function"==typeof r[A])c=t(e,e[A],r[A]);else if(m(s,A)){let r=((e,r)=>function(s,...a){if(a.length<r.minArgs)throw new Error(`Expected at least ${r.minArgs} ${n(r.minArgs)} for ${e}(), got ${a.length}`);if(a.length>r.maxArgs)throw new Error(`Expected at most ${r.maxArgs} ${n(r.maxArgs)} for ${e}(), got ${a.length}`);return new Promise(((n,t)=>{if(r.fallbackToNoCallback)try{s[e](...a,g({resolve:n,reject:t},r))}catch(g){console.warn(`${e} API method doesn't seem to support the callback parameter, falling back to call it without a callback: `,g),s[e](...a),r.fallbackToNoCallback=!1,r.noCallback=!0,n()}else r.noCallback?(s[e](...a),n()):s[e](...a,g({resolve:n,reject:t},r))}))})(A,s[A]);c=t(e,e[A],r)}else c=c.bind(e);else if("object"==typeof c&&null!==c&&(m(r,A)||m(s,A)))c=i(c,r[A],s[A]);else{if(!m(s,"*"))return Object.defineProperty(a,A,{configurable:!0,enumerable:!0,get:()=>e[A],set(r){e[A]=r}}),c;c=i(c,r[A],s["*"])}return a[A]=c,c},set:(r,s,g,n)=>(s in a?a[s]=g:e[s]=g,!0),defineProperty:(e,r,s)=>Reflect.defineProperty(a,r,s),deleteProperty:(e,r)=>Reflect.deleteProperty(a,r)},A=Object.create(e);return new Proxy(A,o)},o=e=>({addListener(r,s,...a){r.addListener(e.get(s),...a)},hasListener:(r,s)=>r.hasListener(e.get(s)),removeListener(r,s){r.removeListener(e.get(s))}}),A=new a((e=>"function"!=typeof e?e:function(r){const s=i(r,{},{getContent:{minArgs:0,maxArgs:0}});e(s)})),l=new a((e=>"function"!=typeof e?e:function(r,s,a){let g,n,t=!1,m=new Promise((e=>{g=function(r){t=!0,e(r)}}));try{n=e(r,s,g)}catch(e){n=Promise.reject(e)}const i=!0!==n&&((o=n)&&"object"==typeof o&&"function"==typeof o.then);var o;if(!0!==n&&!i&&!t)return!1;return(i?n:m).then((e=>{a(e)}),(e=>{let r;r=e&&(e instanceof Error||"string"==typeof e.message)?e.message:"An unexpected error occurred",a({__mozWebExtensionPolyfillReject__:!0,message:r})})).catch((e=>{console.error("Failed to send onMessage rejected reply",e)})),!0})),c=({reject:s,resolve:a},g)=>{e.runtime.lastError?e.runtime.lastError.message===r?a():s(new Error(e.runtime.lastError.message)):g&&g.__mozWebExtensionPolyfillReject__?s(new Error(g.message)):a(g)},x=(e,r,s,...a)=>{if(a.length<r.minArgs)throw new Error(`Expected at least ${r.minArgs} ${n(r.minArgs)} for ${e}(), got ${a.length}`);if(a.length>r.maxArgs)throw new Error(`Expected at most ${r.maxArgs} ${n(r.maxArgs)} for ${e}(), got ${a.length}`);return new Promise(((e,r)=>{const g=c.bind(null,{resolve:e,reject:r});a.push(g),s.sendMessage(...a)}))},d={devtools:{network:{onRequestFinished:o(A)}},runtime:{onMessage:o(l),onMessageExternal:o(l),sendMessage:x.bind(null,"sendMessage",{minArgs:1,maxArgs:3})},tabs:{sendMessage:x.bind(null,"sendMessage",{minArgs:2,maxArgs:3})}},u={clear:{minArgs:1,maxArgs:1},get:{minArgs:1,maxArgs:1},set:{minArgs:1,maxArgs:1}};return s.privacy={network:{"*":u},services:{"*":u},websites:{"*":u}},i(e,d,s)};e.exports=s(chrome)}else e.exports=globalThis.browser},void 0===(a=s.apply(r,[e]))||(e.exports=a)}},r={};function s(a){var g=r[a];if(void 0!==g)return g.exports;var n=r[a]={exports:{}};return e[a].call(n.exports,n,n.exports,s),n.exports}s.n=e=>{var r=e&&e.__esModule?()=>e.default:()=>e;return s.d(r,{a:r}),r},s.d=(e,r)=>{for(var a in r)s.o(r,a)&&!s.o(e,a)&&Object.defineProperty(e,a,{enumerable:!0,get:r[a]})},s.o=(e,r)=>Object.prototype.hasOwnProperty.call(e,r),(()=>{"use strict";var e=s(412),r=s(544);let a;e.contextMenus.create({id:"brisk-download",title:"Download selected links with Brisk",contexts:["selection"]},(()=>null)),e.downloads.onCreated.addListener((async function(s){let a={type:"single",data:{url:s.url,totalBytes:s.totalBytes,cookies:s.cookies}};200===(await(0,r.y$)(a)).status&&await async function(r){await e.downloads.cancel(r).then(g).catch(console.log),await e.downloads.erase({id:r}).then(g).catch(console.log),await e.downloads.removeFile(r).then(g).catch(g)}(s.id)})),e.runtime.onMessage.addListener((e=>a=e)),e.contextMenus.onClicked.addListener((async(e,s)=>{if("brisk-download"===e.menuItemId){let e={type:"multi",data:{downloadHrefs:a}};try{await(0,r.y$)(e)}catch(e){console.error("Failed to send request to Brisk!")}}}));const g=()=>null})()})();
>

**Comment by AminBhst** [comment]
Hey. Which browser are you using? Chrome?

**Comment by martialpeak** [comment]
yes chrome

**Comment by AminBhst** [comment]
You may have installed it incorrectly. If you have a discord account, I have a video guide on how to install it for chrome in my discord faq cahnnel. It may also be your chrome version perhaps? Because the extension itself is fine. I just tested it out myself.

**Comment by AminBhst** [comment]
How did you install it exactly?

**Comment by martialpeak** [comment]
Extract by Winrar go to extension upload it .I use updated chrome. Telegram .WhatsApp  or YouTube  if I installed wrong.can you speak Persian?

**Comment by AminBhst** [comment]
Yeah bro I can speak persian but I'd rather keep it english on my github. I uploaded the tutorial on my telegram channel. You can join it using the link in my github bio. The comment section is also available there.
