### ISSUE TITLE
Make independant fork of this extension = fork and modify the code of Live stream downloader to remove the blacklist to be able to download videos from sites without restrictions please 

### ISSUE THREAD

**Issue by trimechee** [AminBhst/brisk#62]
Hi Mr @AminBhst , I know that my request can be considered outside the main subject but perhaps the project can be inspired by this rare extension hence my request please : make an independent fork around this rare extension or include this rare extension  in Brisk, I am talking about the excellent rare revolutionary extension " Live stream downloader ", because there are very few open source and effective extensions to download videos, the only effective ones are:

cat catch

https://github.com/xifangczy/cat-catch

and

hls-downloader

https://github.com/puemos/hls-downloader

but according to my tests and use for months, the extension " Live stream downloader" :

https://github.com/chandler-stimson/live-stream-downloader

is the most efficient and powerful open source extension especially if we activate the heavy mode "improved media detection" because it was able to detect videos that the other 2 extensions could not detect.......

the problem is that "Live stream downloader" has a blacklist where developers can ask Live stream downloader to add their sites to this blacklist so the extension will no longer be able to download the content of sites added to the blacklist and if many sites are added to the blacklist, the effectiveness of the extension can be affected.....

so our dream please, maybe with the aim of adding this rare extension to Brisk, the dream please is that Mr AminBhst  forks this magnificent extension and removes the blacklist and offers humanity a fork of this rare extension without blacklist that we can use to download from all sites without restrictions please, either as an independent extension fork which can be useful to me because I use Windows 7 OS 32 bits and I unfortunately cannot use Brisk at the moment, or with a view to including it in Brisk because it is the best extension in the world for downloading videos! thank you very much!

a developer had this idea to fork Live stream downloader to remove the blacklist but his extension has not been updated for months:

file-downloader-unleashed :

https://github.com/helloyanis/file-downloader-unleashed

**Comment by AminBhst** [comment]
Hey @trimechee. Regrettably, I won't be able to implement these huge features for a while. I did plan to start working on them but it's getting pretty hard for me to do so. I'll just refer you to the [announcement](https://github.com/AminBhst/brisk/discussions/63) as to why.
