### ISSUE TITLE
NEW DECEMBER 2024 : short selection of the best of the best tools to add new features, options , donwloade streamng video, mpd m3u8 hls parsers .....! 

### ISSUE THREAD

**Issue by trimechee** [AminBhst/brisk#65]
Hi, i was thinking Brisk was in pause hiatus but i see with pleasure our beloved Brisk continue the developement adventire, huge thanks Mr @AminBhst ! 💯 🥇 

so here new updated selection of the best of open source project that can maybe be help to take inspiration and add new features and option, specially the new m3u8 mpd hls parsers , thanks :) :

UPDATE DECEMBER 2024 :

https://github.com/chandler-stimson/live-stream-downloader

https://github.com/helloyanis/file-downloader-unleashed (without blacklist)

https://github.com/xifangczy/cat-catch
https://github.com/xifangczy/cat-catch/blob/master/README_en.md
https://github.com/xifangczy/URLProtocol
https://github.com/nilaoda/N_m3u8DL-RE
https://o2bmm.gitbook.io/cat-catch/docs/invoke

https://github.com/puemos/hls-downloader

https://github.com/54ac/stream-detector ( can export browser cookies to donwload managers ! the developer said he will relaunch and update and enhance the project soon)

https://github.com/zaidka/cliget (cen export browser cookies to donwload managers !)

https://github.com/andy-portmen/open-in-vlc
https://github.com/andy-portmen/native-client 
https://github.com/andy-portmen/external-application-button (can detect embedded streaming video and add referrer, user string agent to the url of detected video tto pt it in media player or maybe download manager)

https://github.com/filecxx/FileCentipede (have powerful extension to detect and download streaming videos)

http://sniffertv.com/docs/
https://sniffertv.com/docs/

https://github.com/mhogomchungu/media-downloader
https://github.com/mhogomchungu/media-downloader/wiki/Extensions

https://github.com/yt-dlp/yt-dlp
https://github.com/iawia002/lux
https://github.com/soimort/you-get
https://www.gnu.org/software/wget/
https://aria2.github.io/

yt-dlp cookies import
https://github.com/coletdjnz/yt-dlp-youtube-oauth2
https://github.com/coletdjnz/yt-dlp-get-pot
https://github.com/seproDev/yt-dlp-ChromeCookieUnlock

https://github.com/pratikpatel8982/yt-dlp-mp4decrypt

https://github.com/un-def/dl-plus

Nicolaasjan yt-dlp fork with in-between releases 
https://github.com/nicolaasjan/yt-dlp
-f bestaudio/worst -x --cookies-from-browser firefox 

ytdl-patched yt-dlp fork with some more features
https://github.com/ytdl-patched/ytdl-patched
-f bestaudio/worst -x --cookies-from-browser firefox 

****************************************************************************************************************
rare powerful mpd m3u8 parsers :

https://github.com/nilaoda/N_m3u8DL-RE
https://github.com/nilaoda/N_m3u8DL-RE-SimpleG
https://github.com/aclap-dev/vdhcoapp/
https://github.com/youwen21/flybird-m3u8downloader
https://github.com/youwen21/flybird-downloader
https://github.com/Momo707577045/m3u8-downloader
https://github.com/llychao/m3u8-downloader
https://github.com/rain-dl/m3u8-downloader
https://github.com/Harlan-H/M3u8Downloader_H

https://github.com/emarsden/dash-mpd-cli
https://emarsden.github.io/dash-mpd-cli/

https://github.com/globocom/m3u8

https://github.com/lanlinju/simple-download

http://sigmafxdx.com/m3u8Sniffer/

https://github.com/selsta/hlsdl

https://github.com/CoolnsX/hls_downloader
https://github.com/kanishka-linux/hlspy
https://github.com/CoolnsX/dra-cla 

https://ytdlp.online/
https://gitlab.com/wizdevgirl1/yt-dlp-web-ui
https://gitlab.com/wizdevgirl1/yt-dlp-web-api

*********************************************************************************************************

https://github.com/AminBhst/brisk

https://github.com/JohnGuoy/Chrono-Download-Manager

3D Youtube Downloader
https://yd.3dyd.com/
3DYD Youtube Source
https://yd.3dyd.com/

https://github.com/downthemall/downthemall
https://code.downthemall.org/

https://github.com/ugetdm/uget
https://sourceforge.net/projects/urlget/

https://www.arrow-dl.com/
https://github.com/setvisible/ArrowDL

https://coccoc.com/en/tai-video
https://coccoc.com/en/
https://coccoc.com/en/pro

https://www.neatdownloadmanager.com/index.php/en/
Support@NeatDownloadManager.com

https://persepolisdm.github.io/
https://t.me/persepolisdm
https://github.com/persepolisdm/persepolis

https://github.com/agalwood/Motrix
https://motrix.app/
https://agalwood.net/

https://xtremedownloadmanager.com/
https://github.com/subhra74/xdm

https://freetubeapp.io/
https://github.com/FreeTubeApp/FreeTube

https://github.com/aandrew-me/ytDownloader
https://ytdn.netlify.app/

https://github.com/ErrorFlynn/ytdlp-interface

https://github.com/KikoPlayProject/KikoPlay

https://github.com/giantpinkrobots/varia
https://giantpinkrobots.github.io/varia/

https://github.com/jeanslack/Videomass
https://jeanslack.github.io/Videomass/

https://github.com/engatec/vdl

https://xdown.org/

https://www.freedownloadmanager.org/fr/
https://github.com/meowcateatrat/elephant
https://free-addons.org/

https://westbyte.com/ida/

https://www.vso-software.fr/products/downloader/

vcapdownloader
https://vcapdl.com/

Open Video Downloader (youtube-dl-gui)
https://github.com/StefanLobbenmeier/youtube-dl-gui
https://github.com/jely2002/youtube-dl-gui

https://github.com/Bluegrams/Vividl
https://sourceforge.net/projects/vividl/

https://o7q.github.io/MediaDownloader/
https://github.com/o7q/MediaDownloader
https://o7q.github.io/o7q/src/stuff/pages/main/index.html

https://github.com/user234683/youtube-local

https://github.com/kanishka-linux/kawaii-player

https://github.com/coslyk/moonplayer

https://github.com/inbasic/bulk-media-downloader
https://github.com/inbasic/turbo-download-manager-v2

https://github.com/ray-lothian/Easy-Video-Downloader
https://webextension.org/listing/easy-video-downloader.html

https://github.com/JohnGuoy/Chrono-Download-Manager
https://github.com/thisssky/chrome-hls
https://github.com/thisssky/jm3u8

https://github.com/Harlan-H/M3u8Downloader_H
https://github.com/Harlan-H/M3u8Downloader_H.Plugins

https://github.com/Harlan-H/BiliDownloader

https://github.com/KurtBestor/Hitomi-Downloader

https://github.com/yt-dlp/yt-dlp/wiki/Forks
https://github.com/yt-dlp/yt-dlp-wiki/blob/master/Plugins.md

https://github.com/BellezaEmporium/query-streamlink
https://github.com/keystroke3/query-streamlink

https://github.com/sebaro/ViewTube
https://github.com/sebaro/SaveTube

ffmpeg nonfree
https://github.com/AnimMouse/ffmpeg-autobuild
https://www.animmouse.com/projects/ffmpeg-autobuild/
https://www.animmouse.com/p/ffmpeg-binaries/
https://github.com/nilaoda/FFmpeg-Builds

https://github.com/pratikpatel8982/AnimeDownloader
https://github.com/pratikpatel8982/yt-dlp-hianime
https://github.com/pratikpatel8982/yt-dlp-mp4decrypt

https://github.com/kemuvx/hianime-dl
https://kemuvx.xyz/
https://t.me/kemuvx

https://github.com/pystardust/ani-cli
https://github.com/Lagradost/cloudstream-3
https://github.com/saikou-app/saikou

https://github.com/LifeActor/ykdl

https://github.com/Kinuseka/GoGo-Downloader-R2
https://kinuseka.us/
https://www.buymeacoffee.com/kinuseka
https://gitlab.com/TrebMcaf

https://github.com/hama3254/Crunchyroll-Downloader-v3.0
https://github.com/anigo-org/anigo-cli
https://github.com/Igglybuff/linky

https://github.com/CoolnsX/dra-cla
https://coolans.dev/
[ansari.tan20@gmail.com](mailto:ansari.tan20@gmail.com)

https://github.com/Benexl/FastAnime
https://www.reddit.com/user/BenX855/

china

https://github.com/lanlinju/Animius

https://github.com/670848654/MoviesBox
https://github.com/670848654/SakuraAnime
[lz670848654@gmail.com](mailto:lz670848654@gmail.com)

https://myani.org/
https://github.com/open-ani/animeko
[support@myani.org](mailto:support@myani.org)
https://github.com/open-ani/ani-website

https://github.com/Momo707577045/m3u8-downloader/blob/master/README-EN.md
https://github.com/Momo707577045/m3u8-downloader
https://github.com/Momo707577045/media-source-extract
http://blog.luckly-mjw.cn/tool-show/m3u8-downloader/index-en.html
http://blog.luckly-mjw.cn/tool-show/index.html
707577045@qq.com

**Comment by AminBhst** [comment]
Hey @trimechee. Yeah brisk is still in a hiatus but only in regards to its major milestones. I still am quite tired so I only occasionally work on some minor improvements and features.
Thank you as always for your recommendations!

**Comment by AminBhst** [comment]
If you don't mind, I have added these recommendations to a list of mine for future reference, so I will be closing this issue now. Thanks again.

**Comment by AminBhst** [comment]
@trimechee Hey so I started working on supporting m3u8 and there are some weird things I've encountered. Almost every u3m8 file I have downloaded so far has had multiple duplicate .ts file segments, some even overlap with each other. Some even have different URLs that point to the same video segment.
I was wondering if you've encountered the same thing in any tools that you've used to download video streams. I could just remove duplicates based on some calculated MD5 hash for each file but I wanted to get your opinion on it in case you've already encountered something like this

**Comment by AminBhst** [comment]
Thanks for your response!
No worries. I just found the motivation to work on it again.
Unfortunately N_m3u8DL-RE  is written in C# so I think it would be difficult to integrate due to the cross-platform issues. I will play around with it to detect all edge-cases and see if I can come up with my own implementation or not. Worst-case scenario, I can just use ffmpeg as a dependency.

**Comment by AminBhst** [comment]
@trimechee
Since you were interested in this feature from the beginning I just wanted to update you on this. The duplication issue was a dumb bug on my implementation lol. Things are going pretty smoothly during the initial development process and I think you can expect m3u8 support in the next major release.
It won't support DRM protected streams but regular streams should be no issue.

**Comment by trimechee** [comment]
@AminBhst !!

Great ! huge thanks and gratitude ! I hope to get a new modern laptop soon in sha Alah to test Brisk !

Brisk is the last hope of open source softwares : meme file centipede has become paid and the free version is not updated .... FDM has sequential download and we can playback video while downnlading but FDM can no longer download vidomoly videos .... xdm, arrowdl, persepolis, ida , motrix....can not download embed streaming videos .....

especially we hope Brisk will be able to merge video and audio because sometimes, streaming platforms put complicated streams with video only and audio only streams .... maybe this command can help and maybe integrated by default if Brisk decides to use ffmpeg to merge audio and video :

ffmpeg -i video.mkv -i audio.mkv -c copy output.mkv

yes no need for DRM ! already drm consumes a lot of resources, in addition I sent you my secret publications like streaming annuaries where we can find thousands of the most secret streaming sites often almost without ads and with their addresses updated so even if disney or amazon prime offer me a free subscription, I refuse because their drm can drain battery heat my cpu fan becomes noisy and I have the most recent streaming videos...

if Brisk decides to use ffmpeg, I found special version of ffmpeg which seems to skip limits of classic ffmpeg :

ffmpeg nonfree
https://github.com/AnimMouse/ffmpeg-autobuild
https://www.animmouse.com/projects/ffmpeg-autobuild/
https://www.animmouse.com/p/ffmpeg-binaries/
https://github.com/nilaoda/FFmpeg-Builds

i post also my secret publication gathering the anime sites because i watch a lot of anime which unfortunately often contain heresy or vulgarity and of course i refuse that, we hope Brisk will be able to support the download of some of these mega rare anime websites please :

https://drive.google.com/drive/folders/1jGp6GcJxZtA63oG0t2fBKsp48MU4tjfU

**Comment by AminBhst** [comment]
Thank you. I do have big plans for Brisks. Hopefully I will start working on BitTorrent after finishing up the live stream download. 
Sure I don't think that would be an issue. If you can find a stream that works like that (video and audio streams are separate) please send me the link so that I can work on supporting that as well. It should be pretty straightforward.

**Comment by trimechee** [comment]
Great ! Thanks so much !

i update again my publication in google drive, i think the same link remains but documents were updated yesterday because i found new links, there are so many! plus a lot of obsolete links so I had to update some links, for my anime publication, I changed organization at the beginning of the French sites, then international sites with multiple integrated subtitles and with English voice then French sites, then animated sites Arab, Polish, Chinese, Russian...

3 years ago I started watching anime because US series are often mediocre and indecent,
I recently discovered the best anime in the world: Initial D, I recommend you watch it, it's the anime that ends the game and surpasses many other famous anime, crazy suspense, there's a movie as season 3, crazy suspense, and the MF Ghost sequel, there's also Danmachi, Wistoria, Stein Gate, Draguon Quest, but we should  be careful, there is unfortunately heresy blasphemy vulgarity indecency in these anime....if we watch to judge anime, we must  watch with extreme caution and don't let yourself be influenced....

the biggest challenge is the anime videos on the hydrax platform, coo coc browser told me it can't support this platform very widespread on streaming anime sites, because small size and good video quality even for 360p quality, I informed the developer of cat catch who confirmed me that this platform is problematic but he didn't refuse to support it..... file centipede told me it can support this platform but I argued with the ungrateful developer, the developer stupidly thinks that when I encounter a problem with another extension, I open an issue in fiel centped issues while it's file centipede that suffers from bugs, in addition the developer is jealous that I help the open source community with the tools that I found, he deleted almost all my issues, he is the loser, he didn't play fair, I deigned to help him because I thought his software was free but i doscover he said his software is paid or will be paid.... very big mistake to have helped him, but I don't understand the source code that we see on its the githb of file centipede , what is it? of an old version and the recent version is paid?

I will open a capital issue to give you ideas to avoid possible censorship problems like those encountered by FDM, thanks !

**Comment by AminBhst** [comment]
Initial D, I've heard heard of it actually. Seems really cool I definitely give it a try. I'll definitely try out the others you mentioned as well. Steins Gate is one of my all-time favorites. I love it. Well I mean the "indecencies" are subjective. If you don't like them you should definitely avoid them and for people that don't mind it is no issue.

I didn't quite get what the problem with hydrax  platform was. What was it that made it hard to work with?

**Comment by AminBhst** [comment]
Also, try not to judge developers that make their software paid. I do love and advocate for free and open-source software, but as a developer, I understand what goes into creating software that's ready for public use. Developers should absolutely have the right to get paid for their work, especially since very few users are willing to donate to keep free and open-source projects alive. It's ultimately their choice and there is nothing wrong with that.
I, myself, have spent an insane amount of my free time developing this project and would definitely love it if I could get paid for it. Especially since maintaining and developing an open-source project alongside a full-time job is difficult. That being said, Brisk is. and will remain free and open-source. I just mentioned these points to prove a point.
I don't know much about file centipede. Maybe the latest versions are paid or some specific features now require payment. I'm not sure.

**Comment by trimechee** [comment]
Please try to understand the context, I do not judge the developers who make free software and on the contrary, I always ask them to display ads in their software or highlight the "donate sponsor" button, even for potplayer which belongs to a large Korean group, I asked them to highlight the sponsor donate button!

I told you my argument with file centipiede is despite the fact that I suspected his software is paid and I have no interest in helping him, because i help only free softwares, there were bugs in his software and I helped him by sending him some tools, by signing the bugs which allows him to improve his software and earn more money, and the guy at the time of recognizing his software is bad, he claims that I encounter these bugs in other softwares and that I, stupidly, I report the bugs of other softwares on his software lol....file centipede did not say clearly if it is paid or not, if I knew it was paid, I would not have even spoken to him, apparently it puts a free version not updated and he said recently that it will divide its software into several parts and make them officially paid, the source code displayed made me think it is a free software,

**Comment by trimechee** [comment]
Mr Amin @AminBhst ,  in screenshot in Brisk page, I see Arabic letters but I don't understand the meaning, I am Arab, so are you Persian or Pakistani? so apparently you are a Muslim, and we must order good and forbid evil, I spoke positively about certain anime because there is suspense but at the same time, there are negative things that we must denounce so that our little brothers, people are not influenced because unfortunately heretic anime, the hero of steingate thinks he is a god and defies destiny, naruto blasphemes destiny, ..... for the beginning, the hero and his comrades have committed bad things and I criticized them publicly on my twitter account, I am fair and balanced,

I have long refused to watch anime but my followers pushed me to watch, so I judge anime and I awaken people's conscience on negative people, not to let their little sister watch the heretic dragon ball anime .... the best is to censor certain passages of anime, the US series are often vulgar, mediocre, nudity, at least anime have better suspense but anime must reject vulgarity, if a character from Naruto, Dragon Ball Bleach, One Piece ..... makes fun of or insults Persian culture or Pakistan which seems to be your country, you will no longer watch any anime Mr. Amin? or a manga author that you like insults Persia or Pakistan in an interview, you will no longer read the manga that you like?

**Comment by trimechee** [comment]
here i explain hysdrax platform problem in cat catch issue : and the dream Brisak can support hydrax videos : 


" 
Hi, so in April, there was many anime hydrax videos in kiss anime site, i tried many downloaders and all fails to download the anime episodes from embedded hydrax videos platform, the last chance was Coc coc browser which have internal downloader With curl, and coc coc downloader fails also :( i contact the Coc coc browser team that said to me this is hydrax videos and coc coc can't donwload hydrax videos and support of hydrax vidoe is not planned..... probably because it is too complex difficult.....

out of curiosity and also out of necessity because i watch vostfr anime and vidmoly platforms in french anime website offers 480p quality 100 mo while kissanime offers 360p quality hydrax video 30 mo with a much smaller and compressed size ideal for my low cpu and weak internet and old windows 7 os, and after all the wonderful commits of our beloved Cat-Catch, I am trying with enthusiasm to download hydrax video from kiss anime site but kiss anime tells me hydrax videos are not available currently.......

i search in the web and i see a lot of complaints from Internet users in the forums who complain that they can not download hydrax videos..... i search and i find a platform of hydrax videos :

https://abyss.to/

there is a demo video of big bucket bunny in abyss site and Cat-Catch can't detect the video and can't download it.....

i discover a developer who invented a special script and a special downloader to download hydrax videos:

https://github.com/PatrickL546/Hydrax-Abyss.to-DownloadHelper-Userscript

https://github.com/PatrickL546/Hydrax-Abyss.to-DownloadHelper-Python

https://github.com/PatrickL546/How-to-download-hydrax-abyss.to

https://requestly.com/

https://www.reddit.com/r/9anime/comments/epvfdf/downloading_from_hydrax/?tl=fr

but the developer recently said hydrax platform has done modifications and his script and downloader do not work anymore and unfortunately, he has just re-archived his repos and the project to support hydrax videos seems abandoned :(

so in a last attempt, I will try to playback the hydrax videos with palemoon and basilisk browsers to see if video lag freeze in my old weak eee pc, and we also hope in the future Cat-Catch will add please support for hydrax videos please, if it's possible obviously and it doesn't tire you too much, because hydrax videos is ideal for downloading anime episodes quickly, for example anime have more than 700 episodes and we need to save space and preserve the ssd and hydrax videos seems to have the most compressed and small size in the world with good video quality , thanks!

i think we can find hydrax videos on these rare anime sites, but recently i haven't tried to find other hydrax videos because kissanime hydrax videos seem to be no longer available currently..... maybe hydrax videos will be available again in the future, or hydrax videos available on other sites like :


https://aniwave.se/
https://aniwave.se/official-app
https://9animetv.to/
https://movies2watch.tv/



https://kissanime.com.ru/
https://kissanime.help/
https://kissasian.si/
https://kisswaifu.app/

https://allmanga.to/


https://hianime.to/home
https://animepahe.ru/
https://animepahe.org/
https://animepahe.com/


https://animixplay.to/
https://everythingmoe.com/
https://theindex.moe/
https://thewiki.moe/
https://fmhy.net/videopiracyguide#anime-streaming






**********************************************************


"Yess, for now, i think supporting hydrax video is not an urgent priority, because the 360p quality of hydrax video is so smooth and so compressed with good video quality that I can playback hydrax videos in my old weak eee pc in catsxp, r3dfox, palemoon, basilisk browsers without lags, freeze, network buffer!! so for now, no need to download hydrax video , unless the hydrax video player no longer offers 360p quality and in this case, streaming becomes impossible and it is necessary to download hydrax HD videos to avoid lags, freezes, network buffers....

I talked about it in April to the developer of file centipede which was my default downloader and which is an open source download manager and has the ability to download streaming videos but file centiede failed to detect an anime hydrax video streaming on the kissanime site and the developer of file centipede thanked me for reporting the problem with hydrax kissanime videos and he told me that this problem can be fixed.....

moreover with file centipede, sometimes the vidmoly video can be detected, sometimes not, and the developer tells me there are no problems and that he can download vidmoly while there may be a browser cache problem ....

so I decided to help this developer by offering him some open source tools mpd m3u8 parsers foudn after many painful research.... which can perhaps help him fix all these problems but the developer shamefully and disgustingly becomes a liar and disrespects me while I help him and he claims by putting a screenshot of a jwplayer video that his software can download hydrax video from kissanime while he has not updated it since February 2023 and he himself confirmed in april that his software cannot download hydrax video and he reveals his spying nature and that he stalks me and expresses his jealousy that I talk to other developers lol .....

so I was shocked and I clashed with this schizophrenic developer of file centipede.....i didn't want to help the developer of file centipede because we have to use activation codes in his software and even if the developer offers free activation codes, I found it weird the activation codes for an open source software and I didn't want to help him but the bugs are piling up and I regret having helped him because he is ungrateful ......

so already file centipede will not add support for hydrax video after my argument with the unfair developer , also for coc coc browser, the development team told me the kissanime video cannot be downloaded because it is a hydrax video and its support is not planned ....

even the powerful alt stream recorder from edge store fails to download hydrax video, and even live stream downloader can't dowload hydrax video, IDM can? i don't like using anymore idm's cracks full of malware viruses that erase registry elements and make the system unstable ....

so i talked about hydrax video just as a possible challenge for the future, or maybe it will become interesting to support hydrax video if censorship becomes even more hellish and relentless and severe and for example censorship will close my favorite streaming platform vidmoly ....



******

"Hi, to download some complex difficult undetectable videos, the solution is either record, a feature offered by some extensions but it can use intensive cpu resources, or, and after my research, it seems the most efficient method, but I don't know if this rare method will be able to download the complicated hydrax videos found on the kissanime site, or this hydrax video demo from big bunny on this hydrax platform :

https://abyss.to/

this exceptional method is made of Mr Momo707577045:

https://github.com/Momo707577045/m3u8-downloader/blob/master/README-EN.md
https://github.com/Momo707577045/m3u8-downloader

https://github.com/Momo707577045/media-source-extract

the problem, the online tool is no longer accessible currently, at least for me who is outside China:

http://blog.luckly-mjw.cn/tool-show/m3u8-downloader/index-en.html

and so this rare technique does not require installing software, just using a website that unfortunately is no longer accessible currently hence my idea that Cat-catch can perhaps apply this rare technique and take advantage of its excellent rare Fmmpeg online website to apply this unusual non-classical download technique:

https://bmmmd.com/

to apply this download method, Mr Momo707577045 explains the steps and what to do precisely, but average users who are not experts may not discover or understand what to do exactly ....

hence my idea that Cat-catch take inspiration or apply this technique of Mr Momo to simplify this whole process in certain cases of complicated videos that are difficult to download...

there is even a greasyfork script that could simplify the process even more but unfortunately the greasyfork link refers to deleted content:

https://github.com/Momo707577045/m3u8-downloader/blob/master/README-EN.md#tampermonkey

https://greasyfork.org/zh-CN/scripts/422237-m3u8-downloader

from what I remember when I discovered this method, for some videos, this method allows us to playback the entire video until the end and so this method can download the video, I find it is better than the "record" feature which can use a lot of resources .....

so to simplify everything make it easier to access all this and realize the ultimate dream of downloading hydrax video that many famous and powerful extensions and download managers fail to detect and download, maybe it may be a good idea that our beloved Cat-cach integrates as a possible option this technique in the case the video is impossible to download by traditional classic means, thanks !

**Comment by AminBhst** [comment]
> Mr Amin @AminBhst , in screenshot in Brisk page, I see Arabic letters but I don't understand the meaning, I am Arab, so are you Persian or Pakistani? so apparently you are a Muslim, and we must order good and forbid evil, I spoke positively about certain anime because there is suspense but at the same time, there are negative things that we must denounce so that our little brothers, people are not influenced because unfortunately heretic anime, the hero of steingate thinks he is a god and defies destiny, naruto blasphemes destiny, ..... for the beginning, the hero and his comrades have committed bad things and I criticized them publicly on my twitter account, I am fair and balanced,
> 
> I have long refused to watch anime but my followers pushed me to watch, so I judge anime and I awaken people's conscience on negative people, not to let their little sister watch the heretic dragon ball anime .... the best is to censor certain passages of anime, the US series are often vulgar, mediocre, nudity, at least anime have better suspense but anime must reject vulgarity, if a character from Naruto, Dragon Ball Bleach, One Piece ..... makes fun of or insults Persian culture or Pakistan which seems to be your country, you will no longer watch any anime Mr. Amin? or a manga author that you like insults Persia or Pakistan in an interview, you will no longer read the manga that you like?

I'm Persian yes but I'm not religious so stuff like that doesn't bother me. Although I can understand why it would bother you since you're muslim and that totally makes sense.

**Comment by AminBhst** [comment]
Regarding hydrax, tbh I currently have no clue what it is that makes downloading its streams so complicated. The only thing I can think of is that they probably have some sort of complex encryption on their m3u8 segments.
Downloading m3u8 streams from sites that have a simple AES-128 encryption or no encryption at all would be pretty straightforward, but more complex encryption would be troublesome. If cat-catch is able to somehow make it work, I'll definitely try to understand their solution and implement it. No guarantees though.

**Comment by trimechee** [comment]
hydrax video is not very important for me , because even if their size is small and video quality is good, sometimes aniwave or kissanime which apparently have hydrax videos do not put French subtitles and I am lazy to look for French subtitles, so I prefer to use French sites in vostfr which include subtitles and the main platform used by my favorite French streaming site is vidmoly , so the most important thing for me is that Brisk supports vidmoly lol :)

the developer of cat catch did not tell me he will support hydrax video, he said this platform is problematic, coc coc browser refused to support hydrax video, I do not know if kissanime has put back the hydrax videos which may have been censored, I even told the developer of cat catch supporting hydrax is not so important and urgent since I use vidmoly, I also spoke about hydrax video to the developer of the live stream downloader extension ....
it's a pity you are not pro religion Mr Amin, our reason for being in this world is to meditate on the creation of Allah and glorify him and worship him obey him, and we will win eternal paradise with the permission of Allah,

the brain that designed Brisk? the computer hardware used to invent Brisk? who created them? it is Allah the one and only Creator, we have a brain and we must use it to meditate on creation and do good things by obeying Allaah, let's not let the devil our enemy who wants our loss make fun of us:
please Mr Amin have a look on my great rare sublime playlist bringing together the beautiful rare recitations of the noble Quran which bring comfort joy happiness:

https://www.youtube.com/playlist?list=PLCVfum9m6K6OkOnoRAzHnz5puRE4zVjWF

an anti religion listened to my playlist and he told me he liked it!

here are the scientific miracles of the Quran and Sunah:

https://kaheel7.com/eng/

we Arabs brought the light of faith and the Persian emperor did not want to pay taxes and recognize the authority of believers and submit, the Persian emperor worshiped fire, the Iranian people freed themselves from the despot, the Iranian people were Sunni and freely chose their Islamic faith and kept their prestigious culture, then unfortunately Shiites ruled Iran and Shiism is not Islam, many Shiite movements are heretics, true Islam is found among the Sunnis and true Islam is loving our mother Aicha and the apostles and obviously loving Ali and we love Hassane and Hussein peace be upon them.

even if the japanese are not muslims, they can make an effort to convey positive moral messages, the hero of steingate who kisses the heroine without marriage, all that is bad .... no honorable man likes his daughter to be kissed by a foreigner, without marriage ;;;;

and obviously it is legitimate developer to be paid, I even told the developer of media downloader to make his software closed source to avoid the theft of his work, I think Brisk should do the same thing, make the code closed and display donate sponsor button to help the development of the project and thank and support the developer for his efforts :)
