### ISSUE TITLE
Collaboration between Mr Amin and Mr Adeli to make the dream become true in sha Allah and have a Brisk version for 32 bits for windows 7 os with VxKex installed please!

### ISSUE THREAD

**Issue by trimechee** [AminBhst/brisk#69]
Hi,  Brisk is finally becoming the best donwloader in the world by adding this  rare feature absent from many  others donwload managers  : "download streaming videos" and also by adding sequential donwload to playbcack temporay donwload while donwloading, thanks great Mr Amin!

the problem I can't test the awesome Brisak because currently using windows 7 OS 32 bits, Mr Amin already explained to me it is difficult to compile a 32 bits version for windows 7 os but there was the generous  Mr Adeii who t generously compiled for me modern softwares which are not compatible with windows 7 os 32 bts and great Mr Adeii made them compatible with windows 7 OS like the download manager "arrowdl", mpq qt, vlc with support of yt dlp, moon player..... :

https://github.com/adeii/Qt6Win7

we can install VxKex which allows us to make modern programs compatible with windows 7 os !!

https://github.com/i486/VxKex
https://github.com/Blaukovitch /VxKex

i don't know if it is technically possible, this is of course very complex, i will open an issue on Mr Adeii's github, but we hope please for a fruitful technical discussion between Mr @AminBhst and Mr @adeii if this dream can become true and maybe Mr Amine can make some modifications to the source code to help Mr Adeii to possibly support legacy windows 7 32-bit os, thanks!

**Comment by AminBhst** [comment]
Hey. Unfortunately, I don't think that will be possible. Flutter doesn't officially support 32 bit so in order to build for 32 bit, I would have to modify and manually compile the entire Flutter Engine with modification and then compile Brisk using that. It's a really non-trivial process that could take a lot of effort and it's not even guaranteed to work properly at the end because of other dependencies and packages that Brisk relies on. Since this is a complicated process, I would much rather focus my limited time on implementing actual features for Brisk.
Hopefully, you'll already have a brand-new PC by the time the live stream download feature is ready.

**Comment by trimechee** [comment]
We undestand, thanks :) 

of course Mr @AminBhst ,  I didn't ask you to compile a version for windows 7 os, because Mr Adeii has the ability to make modern softwares compatible with windows 7 os, I just said it's always good for a compiler to have the developer of the original software at his disposal if ever Mr Adeii encounters a particular difficulty to compile for legacy os, thank you :)

already I don't know Mr Adei's answer to my suggestion because he will have first to accept this challenge and examine the Brisk code and see if it is actually possible to compile for windows 7 os.....

anyway there is no problem, thank you Mr Amin :)  the most important thing is the modern version for windws 11 and it's already a huge job, thanks!

**Comment by AminBhst** [comment]
Yeah sure if he is interested he is welcome to try it out but since Brisk is not a particularly huge and popular project I'm not really optimistic.
No problem. I hope you can get your new PC soon!

**Comment by trimechee** [comment]
Great ! Thanks Mr Amin :) 💯 

Obviously I don't allow myself to tire developers to compile complex softwares just for me, but since I was pleasantly surprised that Mr Adeii succeeded in the feat of compiling complex software like the download manager "arrowdl" for windws 7, there is even updated  google chrome and edge for windows 7 !! so I said to myself maybe there is a minimal chance that he can compile Brisk for windows 7, in any case I had to confirm that Brisk officially becomes the best download manager in history and I think it will be more and more popular, other famous  download managers can't download videos and not updated , even FDM can't download vidmoly videos anymore....Brisk is the best and number 1 :) 💯 🥇
