### ISSUE TITLE
undefined symbol: g_once_init_enter_pointer

### ISSUE THREAD

**Issue by mahdi155000** [AminBhst/brisk#70]
Hello. After the last update to version 2.0.3, every time I run the program, I encounter this error:
`./brisk: symbol lookup error: ./brisk: undefined symbol: g_once_init_enter_pointer`
I have installed all the necessary dependencies related to Debian, and I have not modified the **LD_LIBRARY_PATH** either. I don't know what the problem is.

**Comment by AminBhst** [comment]
Hey. That's weird. I haven't really changed any dependencies from v2.0.2 to v2.0.3. Did it used to work fine on version 2.0.2?
Since you're on debian, the problem might be that you're using older versions of glib and gtk.
Please run this command and let me know what the output is:
```bash
dpkg -l | grep -E 'libglib|libgtk'
```

**Comment by AminBhst** [comment]
According to [this post](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=278663)

g_once_init_enter_pointer is a new symbol since devel/glib20 2.80. Please make sure your glib is not stale.

**Comment by mahdi155000** [comment]
Thank you for quick respond.
I'm on **bookworm** and everything is updated. Also it work properly on 2.0.2. I try to reinstall the glibc packages at least the ones that don't break the system. but nothing happened
here's the result: 
`dpkg -l | grep -E 'libglib|libgtk'
ldd --version
ii  libglib-object-introspection-perl          0.049-3                              amd64        Perl bindings for gobject-introspection libraries
ii  libglib-perl:amd64                         3:1.329.3-2+b2                       amd64        interface to the GLib and GObject libraries
ii  libglib2.0-0:amd64                         2.74.6-2+deb12u4                     amd64        GLib library of C routines
ii  libglib2.0-0:i386                          2.74.6-2+deb12u4                     i386         GLib library of C routines
ii  libglib2.0-bin                             2.74.6-2+deb12u4                     amd64        Programs for the GLib library
ii  libglib2.0-data                            2.74.6-2+deb12u4                     all          Common files for GLib library
ii  libglib2.0-dev:amd64                       2.74.6-2+deb12u4                     amd64        Development files for the GLib library
ii  libglib2.0-dev-bin                         2.74.6-2+deb12u4                     amd64        Development utilities for the GLib library
ii  libglib3.0-cil                             2.99.3-4.1                           amd64        CLI binding for the GLib library of C routines
ii  libglib3.0-cil-dev                         2.99.3-4.1                           amd64        CLI binding for the GLib utility library 2.12
ii  libglibmm-2.4-1v5:amd64                    2.66.5-2                             amd64        C++ wrapper for the GLib toolkit (shared libraries)
ii  libglibutil                                1.0.66                               amd64        Library of glib utilities
ii  libglibutil-dev                            1.0.66                               amd64        Development files for libglibutil
ii  libgtk-3-0:amd64                           3.24.38-2~deb12u3                    amd64        GTK graphical user interface library
ii  libgtk-3-bin                               3.24.38-2~deb12u3                    amd64        programs for the GTK graphical user interface library
ii  libgtk-3-common                            3.24.38-2~deb12u3                    all          common files for the GTK graphical user interface library
ii  libgtk-3-dev:amd64                         3.24.38-2~deb12u3                    amd64        development files for the GTK library
ii  libgtk-4-1:amd64                           4.8.3+ds-2+deb12u1                   amd64        GTK graphical user interface library
ii  libgtk-4-bin                               4.8.3+ds-2+deb12u1                   amd64        programs for the GTK graphical user interface library
ii  libgtk-4-common                            4.8.3+ds-2+deb12u1                   all          common files for the GTK graphical user interface library
ii  libgtk-4-dev:amd64                         4.8.3+ds-2+deb12u1                   amd64        development files for the GTK library
ii  libgtk-vnc-2.0-0:amd64                     1.3.1-1                              amd64        VNC viewer widget for GTK+3 (runtime libraries)
ii  libgtk2.0-0:amd64                          2.24.33-2+deb12u1                    amd64        GTK graphical user interface library - old version
ii  libgtk2.0-bin                              2.24.33-2+deb12u1                    amd64        programs for the GTK graphical user interface library
ii  libgtk2.0-common                           2.24.33-2+deb12u1                    all          common files for the GTK graphical user interface library
ii  libgtk2.0-dev:amd64                        2.24.33-2+deb12u1                    amd64        development files for the GTK library
ii  libgtk3-perl                               0.038-3                              all          Perl bindings for the GTK+ graphical user interface library
ii  libgtkmm-2.4-1v5:amd64                     1:2.24.5-4+b1                        amd64        C++ wrappers for GTK+ 2 (shared libraries)
ii  libgtkmm-3.0-1v5:amd64                     3.24.7-1                             amd64        C++ wrappers for GTK+ (shared libraries)
ii  libgtksourceview-3.0-1:amd64               3.24.11-2+b1                         amd64        shared libraries for the GTK+ syntax highlighting widget
ii  libgtksourceview-3.0-common                3.24.11-2                            all          common files for the GTK+ syntax highlighting widget
ii  libgtksourceview-4-0:amd64                 4.8.4-4                              amd64        shared libraries for the GTK+ syntax highlighting widget
ii  libgtksourceview-4-common                  4.8.4-4                              all          common files for the GTK+ syntax highlighting widget
ii  libgtksourceview-5-0:amd64                 5.6.2-1                              amd64        shared libraries for the GTK 4 syntax highlighting widget
ii  libgtksourceview-5-common                  5.6.2-1                              all          common files for the GTK 4 syntax highlighting widget
ldd (Debian GLIBC 2.36-9+deb12u9) 2.36
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.`

**Comment by AminBhst** [comment]
Right as suspected. Your glib2 version is `2.74.6` and g_once_init_enter_pointer symbol was introduced in `2.80` so it is indeed outdated. This is unfortunately what happens when running stable Linux distros. It comes with the cost of running older versions of almost everything.
The reason it works on 2.0.2 is probably that at the time of building that version, GitHub actions was using an older version of Ubuntu.
Let me see if I can build Brisk on an older version of Ubuntu that uses this glib version. I'll send you the executable file in this issue so that you can test it out to see if it works.

**Comment by AminBhst** [comment]
@mahdi155000
Please test the release available [here](https://github.com/AliML111/brisk/releases/tag/v2.0.3)

**Comment by mahdi155000** [comment]
Yes that successfully worked, thank you.
but is there any other way to do it for the next release I mean. for example build a dummy library to handle this or anything else?

**Comment by mahdi155000** [comment]
Or I can build the package from source my self. But because I'm not familiar with Dart I'll be great full if you can give me a documentation or any pre-dependencies.

**Comment by AminBhst** [comment]
Glad to hear it! No problem.
I will have to test things out to see whether or not suddenly downgrading to an older version for the next release has any side effects. I'm pretty sure it will be fine but still I have make sure. If it proved to be fine, I will downgrade the GitHub actions runner to use Ubuntu-22.04 for future releases so that you can run Brisk without any issues.

**Comment by AminBhst** [comment]
@mahdi155000 I've reverted the compilation process to use ubuntu-22.04. You won't be having this issue anymore for future versions.
