### ISSUE TITLE
[Help Wanted]: Fixing MacOS builds

### ISSUE THREAD

**Issue by sivasoft-cloud** [AminBhst/brisk#74]
Create for MacOs

**Comment by AminBhst** [comment]
I had written the MacOS build pipeline before, however, it doesn't seem to work properly. The output file just fails to execute on a Mac and I have no idea why. I don't own a Mac device so debugging it and testing the output file isn't possible for me.
I'm open to contributions from those who own a Mac and would like to fix the MacOS release pipeline, or any other part of the project that is causing the MacOS build issue.

**Comment by AminBhst** [comment]
After looking into the proper build process for MacOS, I've decided to just forget about MacOS builds. I would love to support the platform but with all the Apple shenanigans when it comes to building for their platform makes it hard to do so. I would require Mac hardware and pay 100$/year for an apple developer account to properly support the platform. It's just nonsensical to be honest. I also don't think there will be a contributor with an apple developer account who is interested in both building and notarizing the executable.
