### ISSUE TITLE
Brisk version 1.2.0 macOS release

### ISSUE THREAD

**Issue by AminBhst** [AminBhst/brisk#8]
The new version of Brisk is now available on the main branch. Could you please upload the macOS binaries to the projects github releases? @Norman-w

**Comment by Norman-w** [comment]
> The new version of Brisk is now available on the main branch. Could you please upload the macOS binaries to the projects github releases? @Norman-w

[have a look](https://github.com/AminBhst/brisk/releases/tag/1.2.0)

**Comment by AminBhst** [comment]
Great! Thank you
