### ISSUE TITLE
Error on Linux

### ISSUE THREAD

**Issue by GrimPixel** [AminBhst/brisk#9]
```
/home/user/Brisk/brisk: error while loading shared libraries: libkeybinder-3.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by AminBhst** [comment]
@GrimPixel Please make sure you have the keybinder-3  package installed. The name of the package for Debian/Ubuntu is ```keybinder-3.0``` and for Fedora/RHEL/CentOS is ```keybinder3```

**Comment by GrimPixel** [comment]
Ahh, thanks. It is called `libkeybinder3` on Arch Linux.

**Comment by 7lilnewbie** [comment]
In Ubuntu the package name is `libkeybinder-3.0-0`
(correction needed in readme)
![image](https://github.com/AminBhst/brisk/assets/145741322/5394b81d-a302-4c86-baf6-24f179af0da8)

**Comment by AminBhst** [comment]
@7lilnewbie Updated the readme. Thanks
